server:
  port: 9001
spring:
  application:
    name: REGISTRY
  cloud:
    discovery:
      enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka/
  instance:
    hostname: registry